### ISSUE TITLE
r2dbc-bom Arabba-SR4 contains SNAPSHOT dependencies

### ISSUE THREAD

**Issue by gsson** [r2dbc/r2dbc-bom#31]
## Bug Report

Arabba-SR4 can't be used for `r2dbc-proxy` without either relying on a SNAPSHOT version (0.8.3.BUILD-SNAPSHOT is in the BOM) or explicitly overriding the version of `r2dbc-proxy`.

See:

https://github.com/r2dbc/r2dbc-bom/blob/Arabba-SR4/pom.xml#L41

I realise SR4 can't be updated, but please keep us non-snapshot cowards in mind for SR5 :)

**Comment by gregturn** [comment]
Agreed. Working on an SR5.

**Comment by gregturn** [comment]
Released.

Waiting on things to sync on maven central.
