### ISSUE TITLE
Prevent use of SNAPSHOT-Dependencies 

### ISSUE THREAD

**Issue by bohni** [r2dbc/r2dbc-bom#33]
## Feature Request

To prevent future use of SNAPSHOT-Dependencies (see #31) you could use [Maven Enforcer Plugin](https://maven.apache.org/enforcer/enforcer-rules/index.html)

#### Is your feature request related to a problem? Please describe
We tried using Spring Boot 2.3.1 and our Build failed because of the enforcer rule mentioned below...

#### Describe the solution you'd like

[Maven Enforcer Plugin Rule](https://maven.apache.org/enforcer/enforcer-rules/requireReleaseDeps.html) should be configured in `pom.xml`

#### Describe alternatives you've considered

Overriding `r2dbc-bom.version` in our pom.xml, see [Spring Boot Issue #22083](https://github.com/spring-projects/spring-boot/issues/22083)

#### Teachability, Documentation, Adoption, Migration Strategy

see Enforcer rule [Require Release Dependencies](https://maven.apache.org/enforcer/enforcer-rules/requireReleaseDeps.html)

**Comment by mp911de** [comment]
Thanks for the issue. We envisioned adding a rule/plugin to our projects to prevent snapshots as it happened with the last release. Do you mind sending a pull request?
